[
   MkGrammar                 -- _1 KW[";"],
   MkGrammar.1:iter-star-sep -- _1 KW[";"],
   Rule                      -- _1 KW["."] _2 KW["::="] _3,
   Rule.3:iter-star          -- _1,
   Terminal                  -- _1,
   NTerminal                 -- _1,
   ListCat                   -- KW["["] _1 KW["]"],
   IdCat                     -- _1,
   LabNoP                    -- _1,
   LabP                      -- _1 _2,
   LabP.2:iter               -- _1,
   LabPF                     -- _1 _2 _3,
   LabPF.3:iter              -- _1,
   LabF                      -- _1 _2,
   Id                        -- _1,
   Wild                      -- KW["_"],
   ListE                     -- KW["["] KW["]"],
   ListCons                  -- KW["("] KW[":"] KW[")"],
   ListOne                   -- KW["("] KW[":"] KW["["] KW["]"] KW[")"],
   ProfIt                    -- KW["("] KW["["] _1 KW["],"] KW["["] _2 KW["]"] KW[")"],
   Ints                      -- KW["["] _1 KW["]"],
   Ints.1:iter-star-sep      -- _1 KW[","],
   Comment                   -- KW["comment"] _1,
   Comments                  -- KW["comment"] _1 _2,
   Internal                  -- KW["internal"] _1 KW["."] _2 KW["::="] _3,
   Internal.3:iter-star      -- _1,
   Token                     -- KW["token"] _1 _2,
   PosToken                  -- KW["position"] KW["token"] _1 _2,
   Entryp                    -- KW["entrypoints"] _1,
   Separator                 -- KW["separator"] _1 _2 _3,
   Terminator                -- KW["terminator"] _1 _2 _3,
   Coercions                 -- KW["coercions"] _1 _2,
   Rules                     -- KW["rules"] _1 KW["::="] _2,
   Rules.2:iter-sep          -- _1 KW["|"],
   Layout                    -- V  [H  [KW["layout"]] _1],
   Layout.1:iter-sep         -- _1 KW[","],
   LayoutStop                -- V  [H  [KW["layout"] KW["stop"]] _1],
   LayoutStop.1:iter-sep     -- _1 KW[","],
   LayoutTop                 -- KW["layout"] KW["toplevel"],
   MkRHS                     -- _1,
   MkRHS.1:iter-star         -- _1,
   MNonempty                 -- KW["nonempty"],
   MEmpty                    -- ,
   RSeq                      -- _1 _2,
   RAlt                      -- _1 KW["|"] _2,
   RMinus                    -- _1 KW["-"] _2,
   RStar                     -- _1 KW["*"],
   RPlus                     -- _1 KW["+"],
   ROpt                      -- _1 KW["?"],
   REps                      -- KW["eps"],
   RChar                     -- _1,
   RAlts                     -- KW["["] _1 KW["]"],
   RSeqs                     -- KW["{"] _1 KW["}"],
   RDigit                    -- KW["digit"],
   RLetter                   -- KW["letter"],
   RUpper                    -- KW["upper"],
   RLower                    -- KW["lower"],
   RAny                      -- KW["char"],
   COMPLETION-Grammar        -- _1,
   COMPLETION-Cat            -- _1,
   COMPLETION-Label          -- _1,
   COMPLETION-LabelId        -- _1,
   COMPLETION-ProfItem       -- _1,
   COMPLETION-IntList        -- _1,
   COMPLETION-Def            -- _1,
   COMPLETION-RHS            -- _1,
   COMPLETION-MinimumSize    -- _1,
   COMPLETION-Reg            -- _1
]